---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
   name: tekton-task-assignment-one-step
spec:
   steps:
      resources: {}
   script: |
        cd /workspace
        mkdir k8s
        cd k8s
        curl https://www.baidu.com
        cat run-steps-as-non-root-alpine-task.yaml
