apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-task-assignment-one-step
 annotations:
    openshift.io/description: 'Assignment for tekton task'
   openshift.io/display-name: tekton-task-assignment
spec:
  steps:
    - image: quay.io/ibmgaragecloud/alpine-curl
      name: one-step : 
      resources: {}
   script: |
        cd /workspace
        mkdir k8s
        cd k8s
        curl https://raw.githubusercontent.com/tektoncd/pipeline/main/examples/v1beta1/taskruns/run-steps-as-non-root.yaml | head -n 24 | sed 's/ubuntu/quay.io\/ibmgaragecloud\/alpine-curl/g' > run-steps-as-non-root-alpine-task.yaml
        cat run-steps-as-non-root-alpine-task.yaml
