---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-task-assignment
  annotations:
    openshift.io/description: 'Assignment for tekton task'
    openshift.io/display-name: tekton-task-assignment
spec:
  steps:
    - image: quay.io/ibmgaragecloud/alpine-curl
      name: retrieve-yaml
      resources: {}
      script: |
        cd /workspace
        mkdir k8s
        cd k8s
        echo "bzinga"
    - image: quay.io/ibmgaragecloud/alpine-curl
      name: extract-task
      resources: {}
      script: |
        cd /workspace/k8s
        touch run-steps-as-non-root-task-only.yaml
        head -n 24 run.yaml > run-nly.yaml
    - image: quay.io/ibmgaragecloud/alpine-curl
      name: swap-image
      resources: {}
      script: |
        cd /workspace/k8s
        cat run-steps-as-non-root-alpine-task.yaml
